export const types = {
    login: 'Auth-login',
    logout: 'Auth-logout',
    initConfig: 'FirstTime-initConfig',
    passedInitConfig : 'FirstTime-passedInit',
    picSetted : 'Auth-picSetted',
    loading : 'Interface-loading',
    removeLoading : 'Interface-Removeloading',
    openPostEntry : 'PostEntry-openPostEntry',
    closePostEntry : 'PostEntry-closePostEntry',
    getPosts : 'Posts-getPosts',
    getUserPosts : 'Posts-getUsersPosts',
    updatePost: 'Posts-update',
    removePost: 'Posts-remove',
    clearPosts: 'Posts-clear',
    addPost: 'Posts-add',
    myPosts : 'Posts-myPosts',
    anyUserPosts : 'Posts-anyUserPosts',
    postStatiticsWOpen : 'PostStatiticsWindow-open',
    postStatiticsWclosed : 'PostStatiticsWindow-closed',
    setReactionsTypeStats : 'PostStatiticsWindow-setReactionStats',
    setProfileData : 'Users-setProfileData',
    removeProfileData : 'Users-removeProfileData',
    updateFollowingProfileData: 'Users-updateFollowing',
    setUsersToSearch : 'search-setUsersToSearch',
    removeUsersToSearch : 'search-removeUsersToSearch',
    setSuggestedUsers : 'following-setSuggestedUsers',
    removeSuggestedUser: 'following-removeSuggestedUsers'
}